# shellcheck shell=bash
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"${XDG_CONFIG_HOME}/java\""
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export GOPATH="${XDG_DATA_HOME}/go"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"
export npm_config_cache="${XDG_CACHE_HOME}/npm"
export PSQL_HISTORY="${XDG_DATA_HOME}/psql_history"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
