[defaults]
binary_only = false
profile = "default"

[packages.alejandra]
asset_pattern = "alejandra-{arch}-unknown-{os}-musl"
github = "kamadorueda/alejandra"
pkg_type = "static"
tag_pattern = "*.*.*"

[packages.btop]
asset_pattern = "btop-{arch}-unknown-{os}-musl.tbz"
github = "aristocratos/btop"
pkg_id = "aristocratos.btop"

[packages.direnv]
asset_pattern = "direnv.{os}-amd64"
github = "direnv/direnv"
pkg_id = "direnv.direnv"

[packages.dra]
asset_pattern = "dra-*-{arch}-unknown-{os}-gnu.tar.gz"
github = "devmatteini/dra"
pkg_type = "archive"
tag_pattern = "*.*.*"

[packages.fastfetch]
asset_pattern = "fastfetch-{os}-amd64.tar.gz"
extract_root = "fastfetch-{os}-amd64"
github = "fastfetch-cli/fastfetch"
pkg_type = "archive"
tag_pattern = "*.*.*"

[packages.fzf]
asset_pattern = "fzf-*-{os}_amd64.tar.gz"
github = "junegunn/fzf"
pkg_id = "junegunn.fzf"

[packages.gentle-ai]
asset_pattern = "gentle-ai_*_{os}_amd64.tar.gz"
github = "Gentleman-Programming/gentle-ai"
pkg_type = "archive"

[packages.git-sync]
asset_pattern = "git-sync_*_{os}_amd64.tar.gz"
github = "AkashRajpurohit/git-sync"
pkg_type = "archive"
tag_pattern = "v*.*.*"

[packages.lazygit]
asset_pattern = "lazygit_*_{os}_{arch}.tar.gz"
github = "jesseduffield/lazygit"
pkg_id = "jesseduffield.lazygit"

[packages.llmfit]
asset_pattern = "llmfit-*-{arch}-unknown-{os}-gnu.tar.gz"
github = "AlexsJones/llmfit"
pkg_type = "archive"
tag_pattern = "v*.*.*"

[packages.pcloud]
pkg_id = "pcloud"
pkg_type = "archive"
url = "https://api.pcloud.com/getpubzip?code=XZ8opl5ZaaYsnBeCX3fLU3v8ngqAv8VMqq7k"
version = "2.0.3"

[packages.pince]
asset_pattern = "*.AppImage"
github = "korcankaraokcu/PINCE"
pkg_type = "appimage"
tag_pattern = "v*.*.*"

[packages.rclone]
asset_pattern = "rclone-*-{os}-amd64.zip"
github = "rclone/rclone"
pkg_id = "rclone.rclone"

[packages.rclone_browser]
asset_pattern = "*{os}-{arch}.AppImage"
github = "kapitainsky/RcloneBrowser"
pkg_type = "appimage"
tag_pattern = "*.*.*"

[packages.savestate]
asset_pattern = "*.AppImage"
github = "Matteo842/SaveState"
pkg_type = "appimage"

[packages.shellcheck]
asset_pattern = "shellcheck-*.{os}.{arch}.tar.gz"
github = "koalaman/shellcheck"
pkg_id = "koalaman.shellcheck"

[packages.shfmt]
asset_pattern = "shfmt_*_{os}_amd64"
github = "mvdan/sh"
pkg_id = "mvdan.shfmt"

[packages.treefmt]
asset_pattern = "treefmt_*_{os}_amd64.tar.gz"
github = "numtide/treefmt"
pkg_type = "archive"
tag_pattern = "v*.*.*"

[packages.use_via]
asset_pattern = "*{os}.AppImage"
github = "the-via/releases"
pkg_type = "appimage"
tag_pattern = "v*.*.*"

[packages.yq]
asset_pattern = "yq_{os}_amd64"
github = "mikefarah/yq"
pkg_id = "mikefarah.yq"
