#!/usr/bin/env bash
# this is the bare bones setup to move everything to XDG dir
# shellcheck disable=SC2034
ZDOTDIR=${HOME}/.config/zsh

# Other XDG paths
export XDG_DATA_HOME=${XDG_DATA_HOME:="${HOME}/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="${HOME}/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="${HOME}/.config"}

# zsh env vars
export ZSH_CACHE_DIR="${XDG_CACHE_HOME}/zsh"

# Default Apps
export EDITOR="zed --wait"
export VISUAL="code -n --wait"
export PAGER="less"

autoload -Uz +X compinit
# functions[compdef]=$'print -u2 \'compdef being called at \'${funcfiletrace[1]}
# '${functions[compdef]}
