[defaults]
binary_only = false
profile = "default"

[packages.PINCE]
asset_pattern = "PINCE-{arch}.*"
github = "korcankaraokcu/PINCE"

[packages.antidot]
asset_pattern = "antidot_*_Linux_{arch}.tar.gz"
github = "doron-cohen/antidot"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "0.6.3"

[packages.betterleaks]
arch_map = { aarch64 = "arm64", x86_64 = "x64" }
asset_pattern = "betterleaks_*_{os}_{arch}.tar.gz"
github = "betterleaks/betterleaks"
tag_pattern = "v*.*.*"
version = "1.8.1"

[packages.ccu]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "ccu-{os}-{arch}"
github = "p-arndt/compose-check-updates"
pkg_type = "binary"
tag_pattern = "*.*.*"
version = "0.9.0"

[packages.dra]
asset_pattern = "dra-*-{arch}-unknown-{os}-gnu.tar.gz"
github = "devmatteini/dra"
pkg_type = "archive"
tag_pattern = "*.*.*"
version = "0.10.2"

[packages.escrcpy]
asset_pattern = "Escrcpy-*-{os}-{arch}.*"
github = "viarotel-org/escrcpy"
version = "3.0.8"

[packages.git-sync]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "git-sync_*_{os}_{arch}.tar.gz"
github = "AkashRajpurohit/git-sync"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "0.21.0"

[packages.glab]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "glab_*_{os}_{arch}.tar.gz"
gitlab = "gitlab-org/cli"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "1.114.0"

[packages.herdr]
asset_pattern = "herdr-{os}-{arch}"
github = "herdrdev/herdr"
tag_pattern = "v*.*.*"
version = "0.8.2"

[packages.irminsul]
asset_pattern = "irminsul-{os}-{arch}.*"
github = "escalonn/irminsul-taioiislop"
tag_pattern = "v*.*.*"
version = "0.2.0-T-1"

[packages.irminsul.hooks]
post_install = "sudo setcap cap_net_raw=ep '$INSTALL_DIR/irminsul'"

[packages.llmfit]
asset_pattern = "llmfit-*-{arch}-unknown-{os}-gnu.tar.gz"
github = "AlexsJones/llmfit"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "1.1.10"

[packages.ls-lint]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "ls-lint-{os}-{arch}.tar.gz"
github = "loeffel-io/ls-lint"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "2.3.1"

[packages.marktext]
asset_pattern = "marktext-{os}-*"
github = "marktext/marktext"
tag_pattern = "v*.*.*"
version = "0.19.1"

[packages.rclone]
version = "1.75.0"

[packages.shellcheck]
version = "0.11.0"

[packages.shfmt]
version = "3.13.1"

[packages.sourcegit]
asset_pattern = "sourcegit-*"
github = "sourcegit-scm/sourcegit"

[packages.treefmt]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "treefmt_*_{os}_{arch}.tar.gz"
github = "numtide/treefmt"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "2.5.0"

[packages.yq]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "yq_{os}_{arch}"
github = "mikefarah/yq"
pkg_id = "mikefarah.yq"
version = "4.53.4"
