[defaults]
binary_only = false
profile = "default"

[packages.antidot]
asset_pattern = "antidot_*_Linux_{arch}.tar.gz"
github = "doron-cohen/antidot"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "0.6.3"

[packages.ccu]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "ccu-{os}-{arch}"
github = "p-arndt/compose-check-updates"
pkg_type = "binary"
tag_pattern = "*.*.*"

[packages.dra]
asset_pattern = "dra-*-{arch}-unknown-{os}-gnu.tar.gz"
github = "devmatteini/dra"
pkg_type = "archive"
tag_pattern = "*.*.*"
version = "0.10.2"

[packages.git-sync]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "git-sync_*_{os}_{arch}.tar.gz"
github = "AkashRajpurohit/git-sync"
pkg_type = "archive"
tag_pattern = "v*.*.*"

[packages.glab]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "glab_*_{os}_{arch}.tar.gz"
gitlab = "gitlab-org/cli"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "1.102.0"

[packages.llmfit]
asset_pattern = "llmfit-*-{arch}-unknown-{os}-gnu.tar.gz"
github = "AlexsJones/llmfit"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "0.9.31"

[packages.pince]
asset_pattern = "*.AppImage"
github = "korcankaraokcu/PINCE"
pkg_type = "appimage"
tag_pattern = "v*.*.*"
version = "0.6.1"

[packages.rclone]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "rclone-*-{os}-{arch}.zip"
github = "rclone/rclone"
pkg_id = "rclone.rclone"
version = "1.74.3"

[packages.rclone_browser]
asset_pattern = "*{os}-{arch}.AppImage"
github = "kapitainsky/RcloneBrowser"
pkg_type = "appimage"
tag_pattern = "*.*.*"

[packages.savestate]
asset_pattern = "*.AppImage"
github = "Matteo842/SaveState"
pkg_type = "appimage"
version = "2.7.1"

[packages.shellcheck]
asset_pattern = "shellcheck-*.{os}.{arch}.tar.gz"
github = "koalaman/shellcheck"
pkg_type = "archive"
tag_pattern = "*.*.*"
version = "0.11.0"

[packages.shfmt]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "shfmt_*_{os}_{arch}"
github = "mvdan/sh"
pkg_id = "mvdan.shfmt"
version = "3.13.1"

[packages.treefmt]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "treefmt_*_{os}_{arch}.tar.gz"
github = "numtide/treefmt"
pkg_type = "archive"
tag_pattern = "v*.*.*"
version = "2.5.0"

[packages.use_via]
asset_pattern = "*{os}.AppImage"
github = "the-via/releases"
pkg_type = "appimage"
tag_pattern = "v*.*.*"

[packages.yq]
arch_map = { aarch64 = "arm64", x86_64 = "amd64" }
asset_pattern = "yq_{os}_{arch}"
github = "mikefarah/yq"
pkg_id = "mikefarah.yq"
version = "4.53.3"
