[tools]
apm = "latest"
"aqua:acheronfail/repgrep" = "latest"
"aqua:cantino/mcfly" = "latest"
"aqua:google/keep-sorted" = "latest"
"aqua:kamadorueda/alejandra" = "latest"
"aqua:numtide/treefmt" = "latest"
bat = "latest"
betterleaks = "latest"
btop = "latest"
bun = "latest"
cocogitto = "latest"
copier = "latest"
cspell = "latest"
direnv = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
git-cliff = "latest"
glab = "latest"
herdr = "latest"
hk = "latest"
lazygit = "latest"
ls-lint = "latest"
node = "latest"
"npm:sort-package-json" = "4.0.0"
prek = "latest"
prettier = "latest"
rclone = "latest"
ripgrep = "latest"
rtk = "latest"
rumdl = "0.2.55"
shellcheck = "latest"
shfmt = "latest"
tmux = "latest"
tombi = "1.4.0"
topgrade = "latest"
typstyle = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
