[hooks]
postinstall = [{ task = "ai-setup-global" }]

[tasks]
# tombi: format.rules.array-values-order = "ascending"
ai-setup-global = [
  "agy plugin install https://github.com/obra/superpowers",
  "claude plugin install paad@paad",
  "claude plugin install superpowers@superpowers-marketplace",
  "claude plugin marketplace add Ovid/paad",
  "claude plugin marketplace add obra/superpowers-marketplace",
  "codex plugin add superpowers@openai-curated",
  "cursor-agent plugin marketplace add https://github.com/obra/superpowers",
  "herdr integration install antigravity-cli",
  "herdr integration install claude",
  "herdr integration install codex",
  "herdr integration install copilot",
  "herdr integration install cursor",
  "herdr integration install hermes",
  "herdr integration install opencode",
  "memorix setup --agent all --global",
  "opencode plugin superpowers@git+https://github.com/obra/superpowers.git -g",
  "rtk init --agent hermes",
  "rtk init -g",
  "rtk init -g --agent cursor",
  "rtk init -g --agent cursor",
  "rtk init -g --codex",
  "rtk init -g --copilot",
  "rtk init -g --gemini",
  "rtk init -g --opencode"
]
# tombi: format.rules.array-values-order = "ascending"
ai-setup-local = ["rtk init -g --agent antigravity"]

[tools]
age = "latest"
apm = "latest"
"aqua:acheronfail/repgrep" = "latest"
"aqua:cantino/mcfly" = "latest"
"aqua:google/keep-sorted" = "latest"
"aqua:kamadorueda/alejandra" = "latest"
"aqua:numtide/treefmt" = "latest"
bat = "latest"
betterleaks = "latest"
btop = "latest"
bun = "latest"
cocogitto = "latest"
copier = "latest"
cspell = "latest"
direnv = "latest"
fastfetch = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
gh = "latest"
git-cliff = "latest"
glab = "latest"
herdr = "latest"
hk = "latest"
lazygit = "latest"
ls-lint = "latest"
node = "latest"
"npm:memorix" = "latest"
"npm:sort-package-json" = "latest"
prek = "latest"
prettier = "latest"
rclone = "latest"
ripgrep = "latest"
rtk = "latest"
rumdl = "latest"
shellcheck = "latest"
shfmt = "latest"
tmux = "latest"
tombi = "latest"
topgrade = "latest"
typos = "latest"
typstyle = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
