#!/usr/bin/env bash
# this is the bare bones setup to move everything to XDG dir
# shellcheck disable=SC2034
ZDOTDIR=${HOME}/.config/zsh

# zsh env vars
export ZSH_CACHE_DIR="${XDG_CACHE_HOME:-${HOME}/.cache}/zsh"
# functions[compdef]=$'print -u2 \'compdef being called at \'${funcfiletrace[1]}
# '${functions[compdef]}
