[commands]
"Hermes Agent" = "hermes update"
"Soar Package Manager" = "soar update"

[firmware]
upgrade = true

[git]
max_concurrency = 1
# tombi: format.rules.array-values-order = "ascending"
repos = ["~/Source-Codes/*/*", "~/Source-Codes/*/*/*"]

[misc]
cleanup = true
disable = ["containers"]
no_self_update = true
notify_each_step = false
