[brew]

[commands]

[composer]

[containers]

[deno]

[distrobox]

[firmware]

[flatpak]

[git]
max_concurrency = 1
# tombi: format.rules.array-values-order = "ascending"
repos = ["~/Source-Codes/*/*", "~/Source-Codes/*/*/*"]

[include]

[julia]

[lensfun]

[linux]

[misc]
cleanup = true
disable = ["containers"]
no_self_update = true
notify_each_step = false

[npm]

[post_commands]

[pre_commands]

[python]

[vagrant]

[vim]

[vscode]

[windows]

[yarn]

[zigup]
